language: node_js
node_js:
  - '12.6.0'
cache:
  directories:
    - 'node_modules'
before_install:
  - openssl aes-256-cbc -K $encrypted_b65ba8847311_key -iv $encrypted_b65ba8847311_iv
  - in deploy_rsa.enc -out deploy_rsa -d
install:
  - npm install
deploy:
  provider: script
  script: .scripts/deploy.sh
  on:
    tags: true
