language: node_js
node_js:
  - '12.6.0'
cache:
  directories:
    - 'node_modules'
addons:
  ssh_known_hosts: 3.16.70.195
before_deploy:
  - openssl aes-256-cbc -K $encrypted_b65ba8847311_key -iv $encrypted_b65ba8847311_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
install:
  - npm install
script:
  - npm build
deploy:
  provider: script
  skip_cleanup: true
  script: .scripts/deploy.sh
  on:
    tags: true
